print ("Nama Saya Deo Permana Putra")
print ("NIM I0322036")
print ("Saya berasal dari Jakarta")
print ("===============================")
print ("Jakarta itu kota yang keren")
print ("Tapi di jakarta mataharinya terada panas banget")
print ("walaupun solo lebih panas dari pada jakarta")
print ("===============================")
print ("harapan saya setelah lulus dari TI adalah mendapatkan pekerjaan yang bagus")